name: Test and Build to push to vercel
on:
  push:
    branches:
      - order-management
  release:
    types: [published]

jobs:
  push_to_registry:
    name: Push Docker image to Docker Hub
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - run: docker network create arkea_api
      - run: docker-compose up
    
      - name: Extract metadata (tags, labels) for Docker
        id: meta
        uses: docker/metadata-action@98669ae865ea3cffbcbaa878cf57c20bbf1c6c38
        with:
          images: ilyesbhd/UserManagementService